Test matrix and one failing expermiental job

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,64 +1,46 @@
-name: Test
+name: "Matrix experiment"
 
-on: [push, pull_request, workflow_dispatch]
+on:
+  push:
+  pull_request:
+  workflow_dispatch:
+
+defaults:
+  run:
+    shell: bash
 
 jobs:
-  build:
-    runs-on: ${{ matrix.os }}
+  tests:
+    name: "py ${{ matrix.python-version }}; dj ${{ matrix.django-version}}"
+    runs-on: "ubuntu-latest"
+    # We expect Django 4.0 to fail, so don't stop if it does.
+    continue-on-error: ${{ matrix.django-version == '4.0' }}
     strategy:
       fail-fast: false
       matrix:
-        python-version: [
-          "3.11-dev",
-          "3.10-dev",
-          "3.9-dev",
-          "3.8-dev",
-          "3.7-dev",
-          "3.7",
-          "3.8",
-          "3.9",
-          "3.10",
-          "pypy-3.8",
-          "pypy-3.9",
-        ]
-        os: [
-          windows-latest,
-          macOS-latest,
-          ubuntu-latest,
-        ]
+        python-version:
+          - "3.9"
+          - "3.10"
+        django-version:
+          - "3.2"
+          - "4.0"
 
     steps:
-      - uses: actions/checkout@v3
-
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
-          cache: pip
-          cache-dependency-path: .github/workflows/test.yml
-
-      - name: Install dependencies
+      - name: "Fake tests"
         run: |
-          python -m pip install -U pip
-          python -m pip install -U pytest
-          python -m pip install -U tqdm
+          echo "Python: ${{ matrix.python-version }}"
+          echo "Django: ${{ matrix.django-version }}"
+          # Django 4.0 doesn't pass yet...
+          if [[ "${{ matrix.django-version }}" == "4.0" ]]; then exit 17; fi
+          echo "Success"
 
-      - name: Test
+  # A final step to give a simple name for required status checks.
+  # https://github.com/orgs/community/discussions/33579
+  success:
+    needs: tests
+    runs-on: ubuntu-latest
+    name: Tests successful
+    steps:
+      - name: "Success"
         run: |
-          python --version
-          python test.py
-          python -m pip --version
-
-      - name: pip cache dir
-        run: |
-          python -m pip cache dir
-
-      - name: "Non-Windows: pip cache dir > /dev/null"
-        if: "!startsWith(matrix.os, 'windows')"
-        run: |
-          python -m pip cache dir > /dev/null
-
-      - name: "Windows: pip cache dir > NUL"
-        if: "startsWith(matrix.os, 'windows')"
-        run: |
-          python -m pip cache dir > NUL
+          echo Tests successful
